# Generated by Django 3.1.5 on 2021-02-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210204_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
